import { MSPData } from '../../types/index.ts';

// Official Minimum Support Prices (MSP) fixed by Government of India (Ministry of Agriculture & CACP)
export const OFFICIAL_MSP_DATA: MSPData[] = [
  {
    id: 'msp-1',
    crop: 'Paddy (Common)',
    cropName: 'Paddy (Common)',
    category: 'Cereals',
    variety: 'Common Grade FAQ',
    season: 'Kharif',
    marketingYear: '2024-25',
    mspValue: 2300,
    mspRate: 2300,
    mspPerKg: 23.0,
    mspRatePerKg: 23.0,
    costOfProduction: 1370,
    returnOverCostPercentage: 68,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-10-01',
    notes: 'Official CACP benchmark (Cost A2+FL + 50% minimum guarantee)',
  },
  {
    id: 'msp-2',
    crop: 'Paddy (Grade A)',
    cropName: 'Paddy (Grade A)',
    category: 'Cereals',
    variety: 'Grade A Superfine',
    season: 'Kharif',
    marketingYear: '2024-25',
    mspValue: 2320,
    mspRate: 2320,
    mspPerKg: 23.2,
    mspRatePerKg: 23.2,
    costOfProduction: 1370,
    returnOverCostPercentage: 69,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-10-01',
    notes: 'Premium grade paddy procurement price',
  },
  {
    id: 'msp-3',
    crop: 'Wheat',
    cropName: 'Wheat',
    category: 'Cereals',
    variety: 'Sharbati / Lokwan FAQ',
    season: 'Rabi',
    marketingYear: '2024-25',
    mspValue: 2275,
    mspRate: 2275,
    mspPerKg: 22.75,
    mspRatePerKg: 22.75,
    costOfProduction: 1105,
    returnOverCostPercentage: 106,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-04-01',
    notes: 'Procurement season benchmark with 105% margin over cost',
  },
  {
    id: 'msp-4',
    crop: 'Maize',
    cropName: 'Maize',
    category: 'Cereals',
    variety: 'Yellow Hybrid',
    season: 'Kharif',
    marketingYear: '2024-25',
    mspValue: 2225,
    mspRate: 2225,
    mspPerKg: 22.25,
    mspRatePerKg: 22.25,
    costOfProduction: 1449,
    returnOverCostPercentage: 54,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-10-01',
    notes: 'National feed & industrial grain MSP standard',
  },
  {
    id: 'msp-5',
    crop: 'Soybean (Yellow)',
    cropName: 'Soybean (Yellow)',
    category: 'Oilseeds',
    variety: 'JS-335 / JS-9560',
    season: 'Kharif',
    marketingYear: '2024-25',
    mspValue: 4892,
    mspRate: 4892,
    mspPerKg: 48.92,
    mspRatePerKg: 48.92,
    costOfProduction: 3182,
    returnOverCostPercentage: 54,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-10-01',
    notes: 'Critical protein & oilseed incentive price',
  },
  {
    id: 'msp-6',
    crop: 'Groundnut',
    cropName: 'Groundnut',
    category: 'Oilseeds',
    variety: 'Bold Pods FAQ',
    season: 'Kharif',
    marketingYear: '2024-25',
    mspValue: 6783,
    mspRate: 6783,
    mspPerKg: 67.83,
    mspRatePerKg: 67.83,
    costOfProduction: 4414,
    returnOverCostPercentage: 54,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-10-01',
    notes: 'Groundnut pod procurement standard price',
  },
  {
    id: 'msp-7',
    crop: 'Gram (Chana)',
    cropName: 'Gram (Chana)',
    category: 'Pulses',
    variety: 'Desi / Desi FAQ',
    season: 'Rabi',
    marketingYear: '2024-25',
    mspValue: 5440,
    mspRate: 5440,
    mspPerKg: 54.4,
    mspRatePerKg: 54.4,
    costOfProduction: 3374,
    returnOverCostPercentage: 61,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-04-01',
    notes: 'Pulse self-sufficiency support standard',
  },
  {
    id: 'msp-8',
    crop: 'Mustard / Rapeseed',
    cropName: 'Mustard / Rapeseed',
    category: 'Oilseeds',
    variety: 'Pusa Bold / Black Mustard',
    season: 'Rabi',
    marketingYear: '2024-25',
    mspValue: 5650,
    mspRate: 5650,
    mspPerKg: 56.5,
    mspRatePerKg: 56.5,
    costOfProduction: 2855,
    returnOverCostPercentage: 98,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-04-01',
    notes: 'High oil yield standard guarantee',
  },
  {
    id: 'msp-9',
    crop: 'Arhar / Tur (Red Gram)',
    cropName: 'Arhar / Tur (Red Gram)',
    category: 'Pulses',
    variety: 'Maruti / Asha FAQ',
    season: 'Kharif',
    marketingYear: '2024-25',
    mspValue: 7550,
    mspRate: 7550,
    mspPerKg: 75.5,
    mspRatePerKg: 75.5,
    costOfProduction: 4791,
    returnOverCostPercentage: 58,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-10-01',
    notes: 'High return pulse crop incentive',
  },
  {
    id: 'msp-10',
    crop: 'Moong (Green Gram)',
    cropName: 'Moong (Green Gram)',
    category: 'Pulses',
    variety: 'Shining Green FAQ',
    season: 'Kharif',
    marketingYear: '2024-25',
    mspValue: 8682,
    mspRate: 8682,
    mspPerKg: 86.82,
    mspRatePerKg: 86.82,
    costOfProduction: 5600,
    returnOverCostPercentage: 55,
    unit: '₹/Quintal',
    source: 'Ministry of Agriculture & Farmers Welfare, GoI',
    effectiveDate: '2024-10-01',
    notes: 'Short duration summer/kharif pulse MSP',
  }
];

export class MSPService {
  static getAllMSP(season?: string, search?: string): MSPData[] {
    let list = [...OFFICIAL_MSP_DATA];
    if (season && season !== 'All') {
      list = list.filter((item) => item.season?.toLowerCase() === season.toLowerCase());
    }
    if (search) {
      const q = search.toLowerCase();
      list = list.filter((item) =>
        (item.crop?.toLowerCase().includes(q) || item.cropName?.toLowerCase().includes(q)) ||
        (item.category && item.category.toLowerCase().includes(q))
      );
    }
    return list;
  }

  static getMSPForCrop(cropName: string): MSPData | undefined {
    const q = cropName.toLowerCase();
    return OFFICIAL_MSP_DATA.find(
      (m) =>
        (m.crop && m.crop.toLowerCase().includes(q)) ||
        (m.cropName && m.cropName.toLowerCase().includes(q)) ||
        q.includes((m.crop || '').toLowerCase().split(' ')[0])
    );
  }
}
